change ipa to tipa

diff --git a/TrollStoreRemoteHelperDemo/md-trollstore b/TrollStoreRemoteHelperDemo/md-trollstore
--- a/TrollStoreRemoteHelperDemo/md-trollstore
+++ b/TrollStoreRemoteHelperDemo/md-trollstore
@@ -4,10 +4,10 @@ DIR=${CODESIGNING_FOLDER_PATH}/../trollbuild
 APP=${CODESIGNING_FOLDER_PATH}
 
 function run_at {
-	pushd $1
-	shift
-	$@
-	popd
+    pushd $1
+    shift
+    $@
+    popd
 }
 
 codesign --remove "${APP}"
@@ -19,7 +19,7 @@ if [ -e "${APP}/embedded.mobileprovision" ]; then
 fi
 
 if [ -z "${CODE_SIGN_ENTITLEMENTS}" ]; then
-	CODE_SIGN_ENTITLEMENTS=${PROJECT_DIR}/${TARGET_NAME}/${TARGET_NAME}.entitlements
+    CODE_SIGN_ENTITLEMENTS=${PROJECT_DIR}/${TARGET_NAME}/${TARGET_NAME}.entitlements
 fi
 
 if [ ! -f "${CODE_SIGN_ENTITLEMENTS}" ]; then
@@ -33,25 +33,25 @@ fi
 echo "use entitlements ${CODE_SIGN_ENTITLEMENTS}"
 
 ldid -S${CODE_SIGN_ENTITLEMENTS} ${APP}/${TARGET_NAME}
-rm -rf ${DIR}/${TARGET_NAME}.ipa ${DIR}/Payload
+rm -rf ${DIR}/${TARGET_NAME}.tipa ${DIR}/Payload
 mkdir -p ${DIR}/Payload
 cp -rf ${APP} ${DIR}/Payload
-run_at ${DIR} "zip -qr ${TARGET_NAME}.ipa Payload"
+run_at ${DIR} "zip -qr ${TARGET_NAME}.tipa Payload"
 rm -rf ${DIR}/Payload
 
-IPA_PATH=${DIR}/${TARGET_NAME}.ipa
+IPA_PATH=${DIR}/${TARGET_NAME}.tipa
 
 if [ ! -f ${IPA_PATH} ]; then
-	echo "build failed"
-	exit -1
+    echo "build failed"
+    exit -1
 fi
 
 if [ ! -z "${TROLLSTORE_DEVICE_IP}" ]; then
-	curl -v ${TROLLSTORE_DEVICE_IP}:1222/install/${TARGET_NAME}.ipa -T ${IPA_PATH}
-	if [ ! $? -eq 0 ]; then
-		echo "install failed"
-		exit -1
-	fi
+    curl -v ${TROLLSTORE_DEVICE_IP}:1222/install/${TARGET_NAME}.tipa -T ${IPA_PATH}
+    if [ ! $? -eq 0 ]; then
+        echo "install failed"
+        exit -1
+    fi
 fi
 
 exit 0
